name: marhaba
description: A new Flutter project.
publish_to: "none" # Remove this if you're planning to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation Packages
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  flutter_native_splash: ^2.3.10
  introduction_screen: ^3.1.12
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.13.1

  # Utilities
  http: ^1.2.1
  shared_preferences: ^2.2.2

  # Voice Assistant
  provider: ^6.1.2
  speech_to_text: ^6.4.0
  flutter_tts: ^4.2.0
  permission_handler: ^11.3.1
  avatar_glow: ^3.0.1

  # Map & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  routing_client_dart: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - data/
    - data/Germany_data.json
    - data/Turkey/
